version: "3.9"

services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/app.db}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL:-admin@example.com}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin}
      - PORT=8400
    ports:
      - "8400:8400"
    volumes:
      - ./:/app
      - app_data:/app/data
    depends_on:
      - db
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8400", "--log-level", "info"]

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-deposits}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  app_data:
